### ISSUE TITLE
undefined method format_value

### ISSUE THREAD

**Issue by cheoAlejo** [MichalVanzura/redmine_app_notifications#23]
A weird error when try to view all the notifications on `see all` link. It happened only on one user.

```
Started GET "/app-notifications" for 186.87.247.60 at 2015-06-24 18:51:09 -0500
Processing by AppNotificationsController#index as HTML
  Current user: luisa (id=10)
  Rendered plugins/redmine_app_notifications/app/views/issues/_issue_edit.html.erb (6.4ms)
  Rendered plugins/redmine_app_notifications/app/views/issues/_issue_edit.html.erb (4.7ms)
  Rendered plugins/redmine_app_notifications/app/views/issues/_issue_edit.html.erb (4.6ms)
  Rendered plugins/redmine_app_notifications/app/views/issues/_issue_edit.html.erb (4.6ms)
  Rendered plugins/redmine_app_notifications/app/views/issues/_issue_edit.html.erb (4.3ms)
  Rendered plugins/redmine_app_notifications/app/views/app_notifications/index.html.erb within layouts/base (2236.4ms)
Completed 500 Internal Server Error in 2244.0ms

ActionView::Template::Error (undefined method `format_value' for #<#<Class:0x0000000520e090>:0x007f03008c8fc0>):
    12: <% @app_notifications.each do |notification| %>
    13:         <div class="notification <%= "new" if !notification.viewed %>">
    14:                 <% if notification.is_edited
```
### My env:

```
Environment:
  Redmine version                2.6.5.stable
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
```

**Comment by Androc** [comment]
If you search ```ActionView::Template::Error (undefined method `format_value'``` in Google, there is a dead link which mentions "Custom field referencing deleted value trigger an error on display".
Maybe you are in same situation, it happens only on one notification that blocks your user.
Try to clean these notifications and test again.

**Comment by cheoAlejo** [comment]
Hey thanks for the answer. I love this plugin, I dont want to stop using it :cold_sweat:

Yes, the problem seems to be related to custom fields. I have one custom field for issues, it's boolean and required. If I edit this custom field for any issue, the notification fails to show and throws an error.

When I click the notificiations top menu link (I changed it for an icon)...
![2015-06-25 12_02_29-delfin redmine](https://cloud.githubusercontent.com/assets/10518807/8360471/8b9d5160-1b32-11e5-951f-b8927135debe.png)
...nothing shows up and throws this error:

```
Started GET "/app-notifications" for 186.87.247.60 at 2015-06-25 11:56:54 -0500
Processing by AppNotificationsController#index as HTML
  Current user: admin (id=1)
  Rendered plugins/redmine_app_notifications/app/views/app_notifications/_ajax.html.erb (1999.6ms)
Completed 500 Internal Server Error in 2006.3ms

ActionView::Template::Error (undefined method `format_value' for #<#<Class:0x007f6915abbd70>:0x00000004555c90>):
    3:  <div id="notificationsBody" class="notifications">
    4:          <% @app_notifications.where(viewed: false).each do |notification| %>
    5:                  <% if notification.is_edited? %>
    6:                          <%= render :partial => 'issues/issue_ajax_edit', :formats => [:html], :locals => { :notification => notification, :journal => notification.journal, :journal_details => details_to_strings(notification.journal.visible_details(notification.author), false, :only_path => false) }%>
    7:                  <% else %>
    8:                          <%= render :partial => 'issues/issue_ajax_add', :formats => [:html], :locals => { :notification => notification }%>
    9:                  <% end %>
  app/helpers/issues_helper.rb:328:in `show_detail'
  app/helpers/issues_helper.rb:277:in `block in details_to_strings'
  app/helpers/issues_helper.rb:263:in `each'
  app/helpers/issues_helper.rb:263:in `details_to_strings'
``` 

Im running a 2.6.5.stable redmine instance, googling I found that since redmine 2.5.x they removed the 
CustomFieldFormat class.
http://www.redmine.org/boards/3/topics/41815
http://www.redmine.org/projects/redmine/repository/revisions/12334

**Comment by Androc** [comment]
Hello I don't have access to a computer before Monday but I will try to
find a solution as soon as possible

Hey thanks for the answer. I love this plugin, I dont want to stop
using it [image:
:cold_sweat:]

Yes, the problem seems to be related to custom fields. I have one custom
field for issues, it's boolean and required. If I edit this custom field
for any issue, the notification fails to show and throws an error.

When I click the notificiations top menu link (I changed it for an icon)...
[image: 2015-06-25 12_02_29-delfin redmine]
<https://cloud.githubusercontent.com/assets/10518807/8360471/8b9d5160-1b32-11e5-951f-b8927135debe.png>
...nothing shows up and throws this error:

Started GET "/app-notifications" for 186.87.247.60 at 2015-06-25 11:56:54 -0500
Processing by AppNotificationsController#index as HTML
  Current user: admin (id=1)
  Rendered plugins/redmine_app_notifications/app/views/app_notifications/_ajax.html.erb
(1999.6ms)
Completed 500 Internal Server Error in 2006.3ms

ActionView::Template::Error (undefined method `format_value' for
#<#<Class:0x007f6915abbd70>:0x00000004555c90>):
    3:  <div id="notificationsBody" class="notifications">
    4:          <% @app_notifications.where(viewed: false).each do
|notification| %>
    5:                  <% if notification.is_edited? %>
    6:                          <%= render :partial =>
'issues/issue_ajax_edit', :formats => [:html], :locals => {
:notification => notification, :journal => notification.journal,
:journal_details =>
details_to_strings(notification.journal.visible_details(notification.author),
false, :only_path => false) }%>
    7:                  <% else %>
    8:                          <%= render :partial =>
'issues/issue_ajax_add', :formats => [:html], :locals => {
:notification => notification }%>
    9:                  <% end %>
  app/helpers/issues_helper.rb:328:in `show_detail'
  app/helpers/issues_helper.rb:277:in `block in details_to_strings'
  app/helpers/issues_helper.rb:263:in `each'
  app/helpers/issues_helper.rb:263:in `details_to_strings'

Im running a 2.6.5.stable redmine instance, googling I found that since
redmine 2.5.x they removed the
CustomFieldFormat class.
http://www.redmine.org/boards/3/topics/41815
http://www.redmine.org/projects/redmine/repository/revisions/12334

—
Reply to this email directly or view it on GitHub
<https://github.com/MichalVanzura/redmine_app_notifications/issues/23#issuecomment-115348308>
.

**Comment by cheoAlejo** [comment]
:wink: Thanks for the answer.

**Comment by Androc** [comment]
I checked what I could do to solve the problem.

At this time I understant that ```Redmine::CustomFieldFormat``` is removed but in favor of ```Redmine::FieldFormat```.
I am not sure why the custom field is not correctly displayed as it is correctly displayed in issue history.

I did several tests but not good enough with Ruby to fully understand the problem and solution.

Still working on it.

**Comment by cheoAlejo** [comment]
Thanks for the effort.

**Comment by iboB** [comment]
@cheoAlejo 

I had the exact same problem. Unfortunately I too, don't know much about the redmine api, so I created a quick patch which works around the issue, at the cost of not displaying detailed information (besides the title) for notifications which would have otherwise caused the crash. 

Here's the patch:

[redmine_app_notif_crash.patch.txt](https://github.com/MichalVanzura/redmine_app_notifications/files/95565/redmine_app_notif_crash.patch.txt)

**Comment by cheoAlejo** [comment]
Thanks, i'll try it. I had to drop custom fields because they were causing troubles with other plugins as well.

**Comment by Soniaz08** [comment]
Hello, 

I have the same problem output when I have updated a custom_field of an issue and I try to display the notification related to this issue.
The error says that it is looking for the method `format_value' which is not located in issues_helper.rb but in custom_fields_helper.rb

To solve this problem, I have add in the controller app_notifications_controller.rb:
`helper :custom_fields`
`helper :issues`

and delete the app_notifications_helper.rb because it will not be necessary anymore.

and it works for me

**Comment by cheoAlejo** [comment]
Hi @Soniaz08 ! thanks for the fix, it works like a charm now. I wonder why you haven't make a pull request with your fix.
